# Generated by Django 5.0.4 on 2024-07-26 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 5, 34, 57, 461950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 5, 34, 57, 460948, tzinfo=datetime.timezone.utc)),
        ),
    ]
