# Generated by Django 5.0.4 on 2024-07-26 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_events_created_at_services_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 6, 6, 55, 471716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 6, 6, 55, 470658, tzinfo=datetime.timezone.utc)),
        ),
    ]
