# Generated by Django 5.0.4 on 2024-07-29 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_events_is_deleted_services_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 4, 51, 52, 16066, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 4, 51, 52, 15034, tzinfo=datetime.timezone.utc)),
        ),
    ]
