# Generated by Django 5.0.4 on 2026-03-21 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_alter_events_created_at_alter_services_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 7, 42, 20, 878851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 7, 42, 20, 878851, tzinfo=datetime.timezone.utc)),
        ),
    ]
