# Generated by Django 5.0.4 on 2024-09-15 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorservices',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 11, 59, 7, 590948, tzinfo=datetime.timezone.utc)),
        ),
    ]
