# Generated by Django 5.0.4 on 2024-08-11 03:29

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
        ('superadmin', '0034_alter_events_created_at_alter_services_created_at'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Customusers',
            fields=[
                ('allusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('managers.allusers',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Total', models.BigIntegerField()),
                ('amount_paid', models.BigIntegerField()),
                ('created_at', models.DateField(default=datetime.datetime(2024, 8, 11, 3, 29, 54, 727001, tzinfo=datetime.timezone.utc))),
                ('rating', models.IntegerField(default=0)),
                ('is_rated', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.events')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.managers')),
                ('services', models.ManyToManyField(blank=True, to='vendors.vendorservices')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.venues')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.booking_status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customusers')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 11, 3, 29, 54, 728003, tzinfo=datetime.timezone.utc))),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorservices')),
            ],
        ),
    ]
