# Generated by Django 5.0.4 on 2024-08-11 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 11, 13, 24, 46, 352415, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='service_rating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 13, 24, 46, 354414, tzinfo=datetime.timezone.utc)),
        ),
    ]
