# Generated by Django 5.0.4 on 2024-09-15 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 9, 15, 11, 59, 7, 591946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='service_rating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 11, 59, 7, 592934, tzinfo=datetime.timezone.utc)),
        ),
    ]
