# Generated by Django 5.0.4 on 2026-03-21 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2026, 3, 21, 7, 42, 20, 878851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='service_rating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 7, 42, 20, 878851, tzinfo=datetime.timezone.utc)),
        ),
    ]
